cinema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cinema_app.urls')),
    path('', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema_app/urls.py
from django.urls import path

from . import views

app_name = 'cinema_app'

urlpatterns = [
    path('', views.main, name='index'),
    path('cinema/', views.cinema, name='cinema'),
    path('movie/', views.movie, name='movie'),
    path('screening/', views.screening, name='screening'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

cinema_app/models.py
from django.db import models

# Create your models here.
# Cinema (name, location, capacity)


class Cinema(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    capacity = models.PositiveIntegerField()

    def __str__(self):
        return self.name
    

# Movie (title (str), director (str), description (str), duration (int), release_date)
class Movie(models.Model):
    title = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    duration = models.PositiveIntegerField()
    release_date = models.DateField()
    cinemas = models.ManyToManyField(Cinema)
    poster = models.ImageField(upload_to='', default='/media/movie_posters/poster.jpg')

    def __str__(self):
        return self.title
    

# Screening (start_time (DateTi­meField), end_time (DateTi­meField))
class Screening(models.Model):
    cinema = models.ForeignKey(Cinema, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def __str__(self):
        return f'{self.movie.title} starting at {self.start_time}, ending at {self.end_time}'

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

cinema_app/forms.py
from django import forms

from .models import Cinema, Movie, Screening

class CinemaForm(forms.ModelForm):
    class Meta:
        model = Cinema
        # fields = ['name', 'location', 'capacity']
        fields = '__all__'
        

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        # fields = ['name', 'location', 'capacity']
        fields = '__all__'


class ScreeningForm(forms.ModelForm):
    class Meta:
        model = Screening
        # fields = ['name', 'location', 'capacity']
        fields = '__all__'
        

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    class Meta:
        model = User
        # fields = ['name', 'location', 'capacity']
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']
        

cinema_app/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import CinemaForm, MovieForm, ScreeningForm

from .models import Cinema, Movie, Screening

# Create your views here.
def main(request):
    page_number = request.GET.get('page', 1)

    cinemas = Cinema.objects.all().order_by('id')
    movies = Movie.objects.all()
    screenings = Screening.objects.all()

    paginator = Paginator(list(movies), 2)
    movies_page = paginator.page(page_number)

    return render(request, 'cinema_app/index.html', {
        'cinemas': cinemas,
        'movies': movies_page,
        'screenings': screenings
    })

@login_required
def cinema(request):
    if request.method == 'POST':
        form = CinemaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cinema_app:index')
        else:
            return render(request, 'cinema_app/cinema.html', {'form': form})
    return render(request, 'cinema_app/cinema.html', {'form': CinemaForm()})

@login_required
def movie(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cinema_app:index')
        else:
            return render(request, 'cinema_app/movie.html', {'form': form})
    return render(request, 'cinema_app/movie.html', {'form': MovieForm()})

@login_required
def screening(request):
    if request.method == 'POST':
        form = ScreeningForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cinema_app:index')
        else:
            return render(request, 'cinema_app/screening.html', {'form': form})
    return render(request, 'cinema_app/screening.html', {'form': ScreeningForm()})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm, LoginForm

# Create your views here.
def register(request):
    if request.user.is_authenticated:
        return redirect(to='cinema_app:index')
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cinema_app:index')
        else:
            return render(request, 'users/register.html', {'form': form})
    return render(request, 'users/register.html', {'form': RegisterForm()})

def login_user(request):
    if request.user.is_authenticated:
        return redirect(to='cinema_app:index')
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='cinema_app:index')

    return render(request, 'users/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='cinema_app:index')

cinema_app/templates/cinema_app/cinema.html
{% extends 'cinema_app/base.html' %}

{% block content %}
<h2>Add a Cinema</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

cinema_app/templates/cinema_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <h1>My cinema manager</h1>
    <a href="{% url 'cinema_app:cinema' %}" role="button">Add a Cinema</a>
    <a href="{% url 'cinema_app:movie' %}" role="button">Add a Movie</a>
    <a href="{% url 'cinema_app:screening' %}" role="button">Add a Screening</a>
    {% if user.is_authenticated %}
        <a href="{% url 'users:logout' %}" role="button">Log out</a>
    {% else %}
        <a href="{% url 'users:register' %}" role="button">Register user</a>
        <a href="{% url 'users:login' %}" role="button">Log in</a>
    {% endif %}
    <h1>All Information</h1>

    <h2>Cinemas</h2>
    <ul>
        {% for cinema in cinemas %}
            <li>{{ cinema.name }} - {{ cinema.location }} - Capacity: {{ cinema.capacity }}</li>
        {% endfor %}
    </ul>

    {% if movies %}
    <ul>
        {% for movie in movies %}
            <li>{{ movie.title }}</li> <!-- Adjust this to display whatever movie fields you want -->
        {% endfor %}
    </ul>

    <div class="pagination">
        <span class="step-links">
            {% if movies.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ movies.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ movies.number }} of {{ movies.paginator.num_pages }}.
            </span>

            {% if movies.has_next %}
                <a href="?page={{ movies.next_page_number }}">next</a>
                <a href="?page={{ movies.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% else %}
    <p>No movies available</p>
{% endif %}
</main>
</body>
</html>

cinema_app/templates/cinema_app/movie.html
{% extends 'cinema_app/base.html' %}

{% block content %}
<h2>Add a Movie</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

cinema_app/templates/cinema_app/screening.html
{% extends 'cinema_app/base.html' %}

{% block content %}
<h2>Add a Screening</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
<h2>Register User</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
<h2>Register User</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}